<html>
<body>

<b><?= html($config->grid->title) ?></b>
<table border="1">
	<tr>
		<? foreach($config->grid->columns->children() as $column=>$empty): ?>
		<th><?= html($column) ?></th>
		<? endforeach ?>
	</tr>
<? foreach($data->item as $item): ?>
	<tr>
		<? foreach($config->grid->columns->children() as $column=>$empty): ?>
		<td><?= html($item->{$column}) ?></td>
		<? endforeach ?>
	</tr>
<? endforeach ?>
</table>

</body>
</html>
